#!/bin/bash
# Node.js provisioning script for Vagrant development VM
# Generated by Vagrant MCP Server

# Node.js version (use LTS by default)
NODE_VERSION="{{NODE_VERSION:-16}}"

echo "Installing Node.js v$NODE_VERSION..."

# Install NVM (Node Version Manager)
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

# Make NVM available in the current shell
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Install Node.js
nvm install $NODE_VERSION
nvm alias default $NODE_VERSION

# Update npm to latest version
npm install -g npm@latest

# Install global packages
npm install -g yarn typescript nodemon ts-node

# Add NVM to shell profile for non-login shells
if [ -f ~/.bashrc ]; then
  grep -q 'NVM_DIR' ~/.bashrc || {
    echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.bashrc
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> ~/.bashrc
    echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' >> ~/.bashrc
  }
fi

if [ -f ~/.zshrc ]; then
  grep -q 'NVM_DIR' ~/.zshrc || {
    echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.zshrc
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> ~/.zshrc
    echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' >> ~/.zshrc
  }
fi

echo "Node.js v$(node -v) has been installed"
echo "npm v$(npm -v) has been installed"
