#!/bin/bash
# Python provisioning script for Vagrant development VM
# Generated by Vagrant MCP Server

# Python version
PYTHON_VERSION="{{PYTHON_VERSION:-3.10}}"

echo "Installing Python $PYTHON_VERSION..."

# Install dependencies
apt-get update
apt-get install -y software-properties-common build-essential zlib1g-dev libncurses5-dev \
    libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev \
    libffi-dev curl libbz2-dev

# Add deadsnakes PPA for different Python versions
add-apt-repository -y ppa:deadsnakes/ppa
apt-get update

# Install Python
apt-get install -y python${PYTHON_VERSION} python${PYTHON_VERSION}-dev python${PYTHON_VERSION}-venv

# Create symbolic link if it doesn't exist
if [[ ! -f /usr/bin/python3 ]]; then
    ln -s /usr/bin/python${PYTHON_VERSION} /usr/bin/python3
fi

# Install pip
curl -sS https://bootstrap.pypa.io/get-pip.py | python${PYTHON_VERSION}

# Create symbolic link if it doesn't exist
if [[ ! -f /usr/bin/pip3 ]]; then
    ln -s /usr/local/bin/pip${PYTHON_VERSION} /usr/bin/pip3
fi

# Install Python tools
pip3 install --upgrade pip
pip3 install virtualenv pipenv poetry

echo "Python $(python3 --version) has been installed"
echo "pip $(pip3 --version) has been installed"
